[build]
  command = "npm run build:static"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Configure secrets scanning to exclude legitimate environment variables
[build.processing.secrets_scanning]
  omit_paths = [
    ".next/cache/webpack/**/*",
    ".next/server/**/*",
    "netlify/functions/chatbot.ts",
    "solution_items/chatbot-service/worker.ts",
    "src/app/api/chatbot/route.ts",
    "src/lib/chatbot-client.ts"
  ]
  omit_keys = ["CHATBOT_MODEL", "CHATBOT_SYSTEM_PROMPT"]

# Netlify Functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/chatbot"
  to = "/.netlify/functions/chatbot"
  status = 200

[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  from = "/api/submit-email"
  to = "/.netlify/functions/submit-email"
  status = 200

# Fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
