[build]
  command = "npm run build:static"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "CHATBOT_MODEL,CHATBOT_SYSTEM_PROMPT"
  SECRETS_SCAN_OMIT_PATHS = ".next/**/*,netlify/functions/**/*,solution_items/**/*,src/**/*"

# Netlify Functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/chatbot"
  to = "/.netlify/functions/chatbot"
  status = 200

[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  from = "/api/submit-email"
  to = "/.netlify/functions/submit-email"
  status = 200

# Fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
